// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Получить JWT ключи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получить JWT ключи",
                "parameters": [
                    {
                        "description": "почта, пароль",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.LoginIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "key pairs",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.LoginOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Получить JWT ключи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получить JWT ключи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "refresh token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "key pairs",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.RefreshOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Зарегистрирует пользователя (врача)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Зарегистрирует пользователя (врача)",
                "parameters": [
                    {
                        "description": "регистрационные данные",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.RegisterIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user_id",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.RegisterOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/download/mri/{id}": {
            "get": {
                "description": "Получение мрт",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "download"
                ],
                "summary": "Получение мрт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id мрт",
                        "name": "mri_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Изображение МРТ",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/download/mri/{mri_id}/image/{image_id}": {
            "get": {
                "description": "Получение image mri",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "download"
                ],
                "summary": "Получение image mri",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id мрт",
                        "name": "mri_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id image",
                        "name": "image_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Изображение кадра Узи",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/med/card": {
            "post": {
                "description": "создать карту",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "создать карту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "данные карты",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/med.PostCardIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id карты",
                        "schema": {
                            "$ref": "#/definitions/med.PostCardOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/med/card/{id}": {
            "get": {
                "description": "Получить карту",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "Получить карту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "patient_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.GetCardOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "обновить карту",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "обновить карту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "patient_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "обновляемые значения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.UpdateCardIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "карта",
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.UpdateCardOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/med/doctors": {
            "get": {
                "description": "Получает информацию о враче",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "Получить информацию о враче",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.GetDoctorOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Обновить врача",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "Обновить врача",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "обновляемые значения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.UpdateDoctorIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "врач",
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.UpdateDoctorOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/med/doctors/patients": {
            "get": {
                "description": "Получить пациентов врача",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "Получить пациентов врача",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "пациенты",
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.GetDoctorPatientsOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/med/patient": {
            "post": {
                "description": "создать пациента",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "создать пациента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "данные пациента",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/med.PostPatientIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id пациента",
                        "schema": {
                            "$ref": "#/definitions/med.PostPatientOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/med/patient/{id}": {
            "get": {
                "description": "Получить пациента",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "Получить пациента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "patient_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.GetPatientOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "обновляет поля пациента",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "med"
                ],
                "summary": "обновляет поля пациента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "patient_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "обновляемые значения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.UpdatePatientIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "пациент",
                        "schema": {
                            "$ref": "#/definitions/internal_api_med.UpdatePatientOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/devices": {
            "get": {
                "description": "получит список mri аппаратов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "получит список mri аппаратов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mri аппараты",
                        "schema": {
                            "$ref": "#/definitions/uzi.GetUziDeviceOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/echographics/{id}": {
            "get": {
                "description": "получает эхографику mri",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "получает эхографику mri",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mri_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "echographics",
                        "schema": {
                            "$ref": "#/definitions/uzi.GetEchographicsOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Обновляет эхографику",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "Обновляет эхографику",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mri_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "обновляемые значения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchEchographicsIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "echographic",
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchEchographicsOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/images/{id}/nodes-segments": {
            "get": {
                "description": "получит ноды и сегменты на указанном изображении",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "получит ноды и сегменты на указанном изображении",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "nodes\u0026\u0026segments",
                        "schema": {
                            "$ref": "#/definitions/uzi.GetUziNodeSegmentsOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/mris": {
            "post": {
                "description": "Загружает узи на обработку",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "Загружает узи на обработку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "mri file. (обязательно с .tiff/.png)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "проекция узи",
                        "name": "projection",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id пациента",
                        "name": "patient_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id узи апапапапарата",
                        "name": "device_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "molodec",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/mris/{id}": {
            "get": {
                "description": "получает mri",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "получает mri",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mri_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mri",
                        "schema": {
                            "$ref": "#/definitions/internal_api_uzi.GetUziOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Обновляет узи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "Обновляет узи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mri_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "обновляемые значения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchUziIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mri",
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchUziOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/mris/{id}/images": {
            "get": {
                "description": "получает списк id кадров mri",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "получает списк id кадров mri",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mri_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "images",
                        "schema": {
                            "$ref": "#/definitions/internal_api_uzi.GetUziImagesOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/mris/{id}/nodes": {
            "get": {
                "description": "получить все узлы узи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "получить все узлы узи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mri_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id узла",
                        "schema": {
                            "$ref": "#/definitions/internal_api_uzi.GetAllNodesOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/nodes": {
            "post": {
                "description": "добавить узел с сегментами",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "добавить узел с сегментами",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "узел с сегментами",
                        "name": "node",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/uzi.PostNodeIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id узла",
                        "schema": {
                            "$ref": "#/definitions/uzi.PostNodeOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/nodes/{id}": {
            "delete": {
                "description": "удалит узел",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "удалит узел",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "molodec",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "обновит узел",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "обновит узел",
                "parameters": [
                    {
                        "description": "узел с сегментами",
                        "name": "node",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchNodeIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "обновленный узел",
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchNodeOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/patient/{id}/mris": {
            "get": {
                "description": "Получить узи пациента",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "Получить узи пациента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "patient_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/uzi.GetPatientUziOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/segments": {
            "post": {
                "description": "добавит новый сегмент к указанному узлу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "добавит новый сегмент к указанному узлу",
                "parameters": [
                    {
                        "description": "сегмент",
                        "name": "node",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/uzi.PostSegmentIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id узла",
                        "schema": {
                            "$ref": "#/definitions/uzi.PostSegmentOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mri/segments/{id}": {
            "delete": {
                "description": "удалит сегмент, ЕСЛИ У УЗЛА НЕ ОСТАНЕТСЯ СЕГМЕНТОВ, ОН ТОЖЕ БУДЕТ УДАЛЕН",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "удалит сегмент",
                "parameters": [
                    {
                        "type": "string",
                        "description": "access_token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "molodec",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "обновит сегмент",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mri"
                ],
                "summary": "обновит сегмент",
                "parameters": [
                    {
                        "description": "узел с сегментами",
                        "name": "node",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchSegmentIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "обновленный узел",
                        "schema": {
                            "$ref": "#/definitions/uzi.PatchSegmentOut"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api_auth.LoginIn": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_api_auth.LoginOut": {
            "type": "object",
            "properties": {
                "access_key": {
                    "type": "string"
                },
                "refresh_key": {
                    "type": "string"
                }
            }
        },
        "internal_api_auth.RefreshOut": {
            "type": "object",
            "properties": {
                "access_key": {
                    "type": "string"
                },
                "refresh_key": {
                    "type": "string"
                }
            }
        },
        "internal_api_auth.RegisterIn": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "org": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_api_auth.RegisterOut": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.GetCardOut": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.GetDoctorOut": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "org": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.GetDoctorPatientsOut": {
            "type": "object",
            "properties": {
                "patients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_med.Patient"
                    }
                }
            }
        },
        "internal_api_med.GetPatientOut": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_uzi_date": {
                    "type": "string"
                },
                "malignancy": {
                    "type": "boolean"
                },
                "policy": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.Patient": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_uzi_date": {
                    "type": "string"
                },
                "malignancy": {
                    "type": "boolean"
                },
                "policy": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.UpdateCardIn": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.UpdateCardOut": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.UpdateDoctorIn": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "org": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.UpdateDoctorOut": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "org": {
                    "type": "string"
                }
            }
        },
        "internal_api_med.UpdatePatientIn": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "last_uzi_date": {
                    "type": "string"
                },
                "malignancy": {
                    "type": "boolean"
                }
            }
        },
        "internal_api_med.UpdatePatientOut": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_uzi_date": {
                    "type": "string"
                },
                "malignancy": {
                    "type": "boolean"
                },
                "policy": {
                    "type": "string"
                }
            }
        },
        "internal_api_uzi.Device": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_api_uzi.GetAllNodesOut": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_uzi.Node"
                    }
                }
            }
        },
        "internal_api_uzi.GetUziImagesOut": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_uzi.Image"
                    }
                }
            }
        },
        "internal_api_uzi.GetUziOut": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "boolean"
                },
                "create_at": {
                    "type": "string"
                },
                "device_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "projection": {
                    "type": "string"
                }
            }
        },
        "internal_api_uzi.Image": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "internal_api_uzi.Node": {
            "type": "object",
            "properties": {
                "ai": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                }
            }
        },
        "internal_api_uzi.Segment": {
            "type": "object",
            "properties": {
                "contor": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                },
                "node_id": {
                    "type": "string"
                }
            }
        },
        "internal_api_uzi.Uzi": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "boolean"
                },
                "create_at": {
                    "type": "string"
                },
                "device_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "projection": {
                    "type": "string"
                }
            }
        },
        "med.PostCardIn": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                }
            }
        },
        "med.PostCardOut": {
            "type": "object",
            "properties": {
                "doctor_id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                }
            }
        },
        "med.PostPatientIn": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "malignancy": {
                    "type": "boolean"
                },
                "policy": {
                    "type": "string"
                }
            }
        },
        "med.PostPatientOut": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "uzi.GetEchographicsOut": {
            "type": "object",
            "properties": {
                "additional": {
                    "type": "string"
                },
                "conclusion": {
                    "type": "string"
                },
                "contors": {
                    "type": "string"
                },
                "echogenicity": {
                    "type": "string"
                },
                "gland_volum": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "isthmus": {
                    "type": "number"
                },
                "left_lobe_length": {
                    "type": "number"
                },
                "left_lobe_thick": {
                    "type": "number"
                },
                "left_lobe_volum": {
                    "type": "number"
                },
                "left_lobe_width": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "regional_lymph": {
                    "type": "string"
                },
                "right_lobe_length": {
                    "type": "number"
                },
                "right_lobe_thick": {
                    "type": "number"
                },
                "right_lobe_volum": {
                    "type": "number"
                },
                "right_lobe_width": {
                    "type": "number"
                },
                "struct": {
                    "type": "string"
                },
                "vascularization": {
                    "type": "string"
                }
            }
        },
        "uzi.GetPatientUziOut": {
            "type": "object",
            "properties": {
                "uzis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_uzi.Uzi"
                    }
                }
            }
        },
        "uzi.GetUziDeviceOut": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_uzi.Device"
                    }
                }
            }
        },
        "uzi.GetUziNodeSegmentsOut": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_uzi.Node"
                    }
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_uzi.Segment"
                    }
                }
            }
        },
        "uzi.PatchEchographicsIn": {
            "type": "object",
            "properties": {
                "additional": {
                    "type": "string"
                },
                "conclusion": {
                    "type": "string"
                },
                "contors": {
                    "type": "string"
                },
                "echogenicity": {
                    "type": "string"
                },
                "gland_volum": {
                    "type": "number"
                },
                "isthmus": {
                    "type": "number"
                },
                "left_lobe_length": {
                    "type": "number"
                },
                "left_lobe_thick": {
                    "type": "number"
                },
                "left_lobe_volum": {
                    "type": "number"
                },
                "left_lobe_width": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "regional_lymph": {
                    "type": "string"
                },
                "right_lobe_length": {
                    "type": "number"
                },
                "right_lobe_thick": {
                    "type": "number"
                },
                "right_lobe_volum": {
                    "type": "number"
                },
                "right_lobe_width": {
                    "type": "number"
                },
                "struct": {
                    "type": "string"
                },
                "vascularization": {
                    "type": "string"
                }
            }
        },
        "uzi.PatchEchographicsOut": {
            "type": "object",
            "properties": {
                "additional": {
                    "type": "string"
                },
                "conclusion": {
                    "type": "string"
                },
                "contors": {
                    "type": "string"
                },
                "echogenicity": {
                    "type": "string"
                },
                "gland_volum": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "isthmus": {
                    "type": "number"
                },
                "left_lobe_length": {
                    "type": "number"
                },
                "left_lobe_thick": {
                    "type": "number"
                },
                "left_lobe_volum": {
                    "type": "number"
                },
                "left_lobe_width": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "regional_lymph": {
                    "type": "string"
                },
                "right_lobe_length": {
                    "type": "number"
                },
                "right_lobe_thick": {
                    "type": "number"
                },
                "right_lobe_volum": {
                    "type": "number"
                },
                "right_lobe_width": {
                    "type": "number"
                },
                "struct": {
                    "type": "string"
                },
                "vascularization": {
                    "type": "string"
                }
            }
        },
        "uzi.PatchNodeIn": {
            "type": "object",
            "properties": {
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                }
            }
        },
        "uzi.PatchNodeOut": {
            "type": "object",
            "properties": {
                "ai": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                }
            }
        },
        "uzi.PatchSegmentIn": {
            "type": "object",
            "properties": {
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                }
            }
        },
        "uzi.PatchSegmentOut": {
            "type": "object",
            "properties": {
                "contor": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                },
                "node_id": {
                    "type": "string"
                }
            }
        },
        "uzi.PatchUziIn": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "boolean"
                },
                "projection": {
                    "type": "string"
                }
            }
        },
        "uzi.PatchUziOut": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "boolean"
                },
                "create_at": {
                    "type": "string"
                },
                "device_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "projection": {
                    "type": "string"
                }
            }
        },
        "uzi.PostNodeIn": {
            "type": "object",
            "properties": {
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                },
                "mri_id": {
                    "type": "string"
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "contor": {
                                "type": "string"
                            },
                            "image_id": {
                                "type": "string"
                            },
                            "knosp012": {
                                "type": "number"
                            },
                            "knosp3": {
                                "type": "number"
                            },
                            "knosp4": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "uzi.PostNodeOut": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "uzi.PostSegmentIn": {
            "type": "object",
            "properties": {
                "contor": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "knosp012": {
                    "type": "number"
                },
                "knosp3": {
                    "type": "number"
                },
                "knosp4": {
                    "type": "number"
                },
                "node_id": {
                    "type": "string"
                }
            }
        },
        "uzi.PostSegmentOut": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Example API",
	Description:      "This is a sample API for demonstration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
